### ISSUE TITLE
support multiple GRPC clients

### ISSUE THREAD

**Issue by farzinfweb** [47monad/sercon#3]
### 📝 Description

Currently, there is no way to pass GRPC client config to the service. Consider a time when the service is a gateway or an aggregator which has to talk to other microservices and for that we need to be able to provide the details of that client as configuration including their endpoints.

### 🔧 Suggested Changes

- Introduce a new GRPC clients map to the cue config files
-  Add the map to the main config and attach env variables

### 📌 Example (new structure)

This is the sort of thing we should end up having:
```yaml
grpc-client:
  - users:
    endpoint: 8080
    timeout: 30s
  - products:
    endpoint: 9090
    timeout: 10s
```

### 🛠 Benefits

- Prevent hard-coding client information inside the code
- Prevent developing custom solutions for such use cases
